FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
# Installer toutes les dépendances nécessaires
RUN npm install && npm install axios bootstrap --save

COPY . .

# Modifier le script build pour ignorer la vérification TypeScript
RUN sed -i 's/"build": "tsc -b && vite build"/"build": "vite build"/' package.json

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]